# Site wide configuration

title:  "Kyle Lo | Statistician"
description:  "My personal site for thoughts on statistics and machine learning."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en_US
url:  "//kyleclo.github.io"

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name:  "Kyle Lo"
  avatar: "bio-photo.jpg"
  bio:  "I am a Statistician / Data Scientist on the Research Team at CDK Global in Seattle.  I graduated in June 2015 with a Master's degree in Statistics from the University of Washington."
  location:  "Seattle, WA"
  email:  "kyleclo@uw.edu"
  linkedin:  "kylelo"
  github:  "kyleclo"
  twitter:
  google:
    ad-client:
    ad-slot:
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
